version: '3'
services:
#  app:
#    build: .
#    volumes:
#      - .:/app
#    ports:
#      - '8000:8000'
#    environment:
#      - ENVIRONMENT=${ENVIRONMENT}
  db:
    image: mysql:8.0
    platform: linux/x86_64
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'db'
      TZ: 'Asia/Tokyo'
volumes:
  mysql_data:
